FROM node:latest as builder

COPY package.json package.json ./
RUN npm install --only=prod&& mkdir /webclient && mv ./node_modules ./webclient

WORKDIR /webclient

COPY . .

RUN npm run build

# Installing NGINX and serving static content
FROM nginx:latest

COPY --from=builder /webclient/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
