version: '3'
services: 
    database:
        image: "postgres"
        build: 
            context: ./db
            dockerfile: dockerfile-postgres
        restart: always
        env_file: 
            - .env
        environment: 
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_HOST_AUTH_METHOD
            - POSTGRES_DB
        ports: 
            - ${POSTGRES_DEFAULT_PORT}:${POSTGRES_DEFAULT_PORT}

    backend:
        image: "backend"
        build: 
            context: ./backend
            dockerfile: dockerfile-backend
        container_name: backend
        env_file: 
            - .env
        environment: 
            - EXPRESS_DEFAULT_PORT
        ports: 
            - ${EXPRESS_DEFAULT_PORT}:${EXPRESS_DEFAULT_PORT}

    webclient:
        image: "webclient"
        build: 
            context: ./webclient
            dockerfile: dockerfile-webclient
        container_name: webclient
        env_file: 
            - .env
        environment: 
            - NODE_ENV
            - REACT_DEFAULT_PORT
        ports: 
            - ${REACT_DEFAULT_PORT}:${REACT_DEFAULT_PORT}