version: '3'
services: 
    postgres:
        image: "postgres"
        build: 
            context: ./db
            dockerfile: dockerfile-postgres
        labels: 
            - "hf"
        container_name: "postgres_service"
        restart: always
        env_file: 
            - .env
        environment: 
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_HOST_AUTH_METHOD
            - POSTGRES_DB
        ports: 
            - ${POSTGRES_DEFAULT_PORT}:${POSTGRES_DEFAULT_PORT}

    express:
        image: "express"
        build: 
            context: ./backend
            dockerfile: dockerfile-backend
        labels: 
            - "hf"
        container_name: "express_service"
        env_file: 
            - .env
        environment: 
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_HOST_AUTH_METHOD
            - POSTGRES_DB
            - POSTGRES_DEFAULT_PORT
            - EXPRESS_DEFAULT_PORT
        links: 
            - postgres
        ports: 
            - ${EXPRESS_DEFAULT_PORT}:${EXPRESS_DEFAULT_PORT}

    webclient:
        image: "webclient"
        build: 
            context: ./webclient
            dockerfile: dockerfile-webclient
        labels: 
            - "hf"
        container_name: "webclient_service"
        env_file: 
            - .env
        environment: 
            - NODE_ENV
            - REACT_DEFAULT_PORT
        links: 
            - express
        ports: 
            - ${REACT_DEFAULT_PORT}:${REACT_DEFAULT_PORT}